	PROCESSOR 16F876A
	INCLUDE <P16F876A.INC>
	__CONFIG _XT_OSC & _WDT_OFF & _PWRTE_OFF & _CP_OFF & _LVP_OFF & _BODEN_OFF  

CNT EQU 0x20 ;CHARACTER COUNTER

	ORG 0x000
	GOTO INIT ;INCLUDE THE LCD DRIVER AND GOTO INIT ROUTINE
	INCLUDE <LCD_DRIVER.INC>
	
INIT:
	CALL LCD_INIT ;FIRST OF ALL WE HAVE TO INITIALIZE LCD
	CLRF CNT ;CLEAR CHAR COUNTER

MAIN:
	MOVLW 0x30 ; CHAR '0' = 0x30
	MOVWF CNT
AGAIN:
	MOVF CNT, W ;WE PASS THE ASCII CODE TO LCD_CHAR TROUGH W REG
	CALL LCD_CHAR ;LCD_CHAR WRITES AN ASCII CODE CHAR TO THE LCD, THE LCD uC WILL THEN AUTOINCREMENT THE CURSOR
	CALL DEL250 ;DO 250MS DELAY, JUST FOR THE EFFECT

	INCF CNT ;LOAD NEXT DIGIT
	MOVLW 0x3A ;LAST DIGIT '9' = 0x39, NEXT VALUE 0x3A
	XORWF CNT, W ;WHEN CNT = 0x3A, IT MEANS WE REACHED THE LAST DIGIT
	BTFSS STATUS, Z
	GOTO AGAIN

	CALL LCD_CLR ;CLEAR LCD
	CALL LCD_L1 ;MOVE CURSOR TO 1ST ROW
	CALL DEL250 ;DO 250MS DELAY
	GOTO MAIN
	
	END
